[programs.localnet]
messengerapp = "9Qz4oEpqoFZPMyws9gkcvE4xFvGrwkJn3xqAtrKY4Anb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/michi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
